packages:
  - software/prepare-fasta
  - software/add-header
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/model": ^1.31.16
  "@platforma-sdk/ui-vue": ^1.31.16
  "@platforma-sdk/workflow-tengo": ^4.7.1
  "@platforma-sdk/block-tools": ^2.5.50
  "@platforma-sdk/test": ^1.31.16
  "@platforma-sdk/tengo-builder": ^2.1.7
  "@platforma-sdk/package-builder": ^2.16.0
  "@platforma-sdk/eslint-config": ^1.0.3
  "@milaboratories/graph-maker": ^1.1.101

  '@milaboratories/software-pframes-conv': ^2.2.2
  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7

  "@platforma-open/soedinglab.software-mmseqs2": ^1.0.0

  '@biowasm/aioli': ~3.2.1
  
  "sass-embedded": ^1.77.8
  
  "vue": ^3.5.13
  "vue-tsc": ^2.2.8
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.4.4

  "vite": ^6.2.2
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "js-yaml": ^4.1.0

  "@changesets/cli": ^2.28.1
